name: Run Xiaobot Scraper

on:
  schedule:
    - cron: '0 15 * * *'  # 每天 UTC 15:00 运行 (相当于北京时间 23:00)
  push:
    paths:
      - 'authors.txt'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 notion-client
    - name: Run scraper
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: python src/scraper.py  # 更新脚本路径